### PR TITLE
(feat) Added optional star style prop

### PR DESCRIPTION
**Pull request by alvaromb**
Adds new `starStyle` prop to configure the style of the stars.

(feat) Added optional star style prop
(doc) Added new prop to the docs

### CODE REVIEW

**Comment by anceque** [comment]
@djchie hey, do you think this request could be merged? It is quite useful to have a custom styling props..

**Comment by djchie** [comment]
@anceque I'm working on getting another update soon and do plan to pull this in. Thanks for the reminder!

**Comment by djchie** [comment]
Thanks for contributing! 😊

**Comment by alvaromb** [comment]
Thanks!

**Pull request merged**
